version: '3.8'
services:
  db:
    image: postgres:16
    container_name: authsome-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authsome
      TZ: 'Asia/Tokyo'
    ports:
      - '5432:5432'
    volumes:
      - ./docker/db:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./docker/nest.dockerfile
    container_name: authsome-backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # .envの値を上書きしたい場合のみここに記載
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: pnpm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/front.dockerfile
    container_name: authsome-frontend
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      # .envの値を上書きしたい場合のみここに記載
      VITE_API_URL: http://localhost:3000
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm run dev -- --host
